### ISSUE TITLE
AWS SecurityHub error importing json with no lastObservedAt

### ISSUE THREAD

**Issue by Enigmatyk** [DefectDojo/django-DefectDojo#3276]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
Internal error 500 when importing AWS SecurityHub json file. 

**Steps to reproduce**
1. Export AWS SecurityHub json file with aws securityhub get-findings --output json
2. Findings > Importing Scan results
3. Select AWS SecurityHub
4. Upload json file retrieved from aws cli command. 

**Expected behavior**
Importing the results successfully. 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Amazon Linux 2]
 - DefectDojo Commit Message: [2020-11-12 18:05:42 +0100] d7523e1d: minikube/k8s action improvement (#3251) [ (HEAD -> master, origin/release/1.9.3, origin/master, origin/HEAD)]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/5115163/99383629-6fdc1380-28ce-11eb-8349-0febc76ef124.png)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

Json file can't be provided it included sensitive data.

**Comment by valentijnscholten** [comment]
can you anonymize the report that is causing the issue? otherwise we can't really see what's going on.

**Comment by Enigmatyk** [comment]
Sorry it is a ~5MB file with 7 million lines it will be difficult to anonymize everything (this file includes all the aggregated results on securityhub it includes inspector findings, CIS benchmarks, config and guard duty). 
I exported the results from another account with way less information and it worked well.

**Comment by valentijnscholten** [comment]
fix PR created, cause by `lastObservedAt` missing for findings and then a bug in the parser trying to set a default value.

**Comment by valentijnscholten** [comment]
Fixed in dev, so 1.10.0

**Comment by Enigmatyk** [comment]
Thanks for the correction sill the bug is not solved.

uwsgi_1         | ValueError: time data '2020-10-01T17:09:11Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'


![image](https://user-images.githubusercontent.com/5115163/99850577-e5214000-2b7d-11eb-8e0f-6795d2e76ece.png)

**Comment by valentijnscholten** [comment]
Well if you don't supply a file to reproduce, it's just trial and error. Could you provide a file to reproduce so we can fix everything in one go? Thank you.

**Comment by Enigmatyk** [comment]
Solved. AWS security and other components use a different time format.
dojo/tools/awssecurityhub/parser.py +62

 if finding.get('Compliance', {}).get('Status', "PASSED"):
        if finding.get('LastObservedAt', None):
            try:
                mitigated = datetime.strptime(finding.get('LastObservedAt'), "%Y-%m-%dT%H:%M:%S.%fZ")
            except:
                mitigated = datetime.strptime(finding.get('LastObservedAt'), "%Y-%m-%dT%H:%M:%fZ")
        else:
            mitigated = datetime.utcnow()
    else:
        mitigated = None
