### ISSUE TITLE
Installing Dev version of DefectDojo results in an Error

### ISSUE THREAD

**Issue by PavitraRaj** [DefectDojo/django-DefectDojo#851]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

## Issue Template
While installing Dev version of DefectDojo from github location https://github.com/DefectDojo/django-DefectDojo/tree/dev, we are facing an issue like the below:

/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 107: cd: /opt/dojo/django-DefectDojo: No such file or directory
==============================================================================
Creating dojo/settings/settings.py and .env file
==============================================================================

/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 124: cd: /opt/dojo/django-DefectDojo: No such file or directory
cp: cannot stat 'dojo/settings/settings.dist.py': No such file or directory
/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 151: cd: /opt/dojo/django-DefectDojo: No such file or directory
DB URL is:
mysql://dojodbusr:OYN%29cVTb%29RMuCIL%290heEb52p@localhost:3306/dojodb
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
==============================================================================
Installing DefectDojo Django application
==============================================================================

Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (18.1)
Directory '.[mysql]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 257: entrypoint_scripts/common/setup-superuser.expect: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/mnt/c/django-DefectDojo-dev/django-DefectDojo-dev/entrypoint_scripts/os/linux.sh: line 279: cd: components: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

### Steps to Reproduce
1. Clone the github directory https://github.com/DefectDojo/django-DefectDojo/tree/dev 
2. Install on Ubuntu On Windows.

**Comment by PavitraRaj** [comment]
Has anyone faced this issue?

**Comment by aaronweaver** [comment]
Fixed in dev and push soon to master. Thanks to Hendrik Mallow's assistance.

**Comment by Chan9390** [comment]
I am still facing this issue when I am trying to do a fresh install of DefectDojo in Ubuntu 18.04 

![image](https://user-images.githubusercontent.com/12944530/82124508-006d5600-97bd-11ea-8916-c2e07a9feb25.png)
